# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VTC NEWS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VTC NEWS
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'GoogleAds-IMA-iOS-SDK'
  pod 'SnapKit'
  pod 'GoSwiftyM3U8'
  pod 'SwiftEventBus'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  # add pods for any other desired Firebase products
  pod 'SnapKit'
  # https://firebase.google.com/docs/ios/setup#available-pods
  target 'VTC NEWSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VTC NEWSUITests' do
    # Pods for testing
  end

end
